language: python
cache: pip
python:
    - "3.6"
addons:
  apt:
    packages:
    - google-chrome-stable
before_install:
- pip3 install pytest-html
- pip3 install selenium
- pip3 install pytest
- wget http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
- mkdir chromedriver
- unzip chromedriver_linux64.zip -d chromedriver/
- export PATH=$PATH:$PWD/chromedriver
before_script:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1366x768x16"
script:
- py.test --html=results/report.html tests/test_qa_position.py